spring:
  application:
    name: GisJkhExchanging
  profiles:
    active: default
server:
  port: 8090

application:
  store:
    trust:
      type: CertStore
    key:
      type: REGISTRY
  client:
    defaultUri: https://api.dom.gosuslugi.ru/
    pooling:
      connection:
        total: 10
        perRoute: 10
    timeout:
      socket: 60
      connection: 30
      request: 30
logging:
  level:
    ru:
      khaksbyt: debug